sudo: required
services: 
    - docker
before_install: 
    - docker build -t abhishekjha26/docker-react -f DockerFile.dev .

script:
    - docker run -e CI=true abhishekjha26/docker-react npm run test
