sudo: required
services: 
    - docker
before_install: 
    - docker build -t abhishekjha26/docker-react -f DockerFile.dev .

script:
    - docker run -e CI=true abhishekjha26/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "Docker"
    env: "Docker-env"
    bucket_name: "abhishekDocker"
    bucket_path: "Docker"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_key_id:
        secure: "$AWS_SECRET_KEY"
